valid_content_types: {
  content_type_video: [ 'video/mp4','video/quicktime','video/3gpp2','video/3gp', 'video/3gpp', 'video/ogg', 'video/webm', 'video/x-flv', 'application/octet-stream'],
  content_type_audio: [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3' ],
  content_type_pdf:   [ 'application/pdf' ],
  content_type_image: [ 'image/jpg', 'image/jpeg', 'image/png', 'image/gif', 'image/x-png' ]
}

file_icons: {
['image/jpg', 'image/jpeg', 'image/png', 'image/gif', 'image/x-png']: 'fa fa-file-image-o',
['application/pdf']: 'fa fa-file-pdf-o',
['audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3']: 'fa fa-file-audio-o',
['video/mp4','video/quicktime','video/3gpp2','video/3gp', 'video/3gpp', 'video/ogg', 'video/webm', 'video/x-flv', 'application/octet-stream']: 'fa fa-file-movie-o'
}

mobile_usa_code: '+1'
mobile_pak_code: '+92'

gmail_username: "ENV['EMAIL_USERNAME']"
gmail_password: "ENV['EMAIL_PASSWORD']"
address: "smtp.gmail.com"
port: 587
domain: 'gmail.com'

production_username: 'xxx'
production_password: 'xxx'
production_domain: 'xxx'

attachment_default_url: '/assets/missing.png'
pakistan_caste: ["Ashkani","Bahawalanzai","Kamboh","Barazani","Barr","Bijarani","Buledi","Bulfati","Buzdar","Chhalgari",
"Damanis","Darzada","Dehwar","Domki","Gujjar","Gabol","Gadhi","Gashkori","Ghazini","Gurmani","Jagirani","Jalbani",
"Jamali","Jarwar","Jatoi","Jiskani","Kalmati","Kalpar","Kambarzahi","Kashani","Kenagzai","Khalol","Kheazai","Khetran",
"Khosa","Khushk","Korai","Khara","Langhani","Lanjwani","Loharani","Lund","Marri","Minhas","Magsi","Mugheri","Nizamani",
"Nothazai","Pitafi","Qaisrani","Qalat","Rahija","Rahmanzai","Rind","Sadozai","Saifi","Sanjrani","Sethwi","Shambhani",
"Sherzai","Shirani","Talpur","Umrani","Wadeyla","Zardari","Bangulzai tribe","Bizenjo tribe","Bahrani tribe","Hasni",
"Jhalawan","Kharal","Kurd","Lango","Lehri","Mirwani","Mengal","Muhammad Shahi","Muhammed Hasni","Raisani","Rodini",
"Sarpara","Sasooli","Shahwani","Sumalani","Gujjar","Alpial","Bhatia","Gabol","Hiraj","Kaira","Karlal","Kathia",
"Khatana","Khloro","Kohli","Lakhani","Malhotra","Memon","Patel","Wassan","Mir","Dar","Kashmiri Shaikh","Khan","Lone",
"Butt","Malik clan (Kashmir)","Wani","Ansari","Arain","Awan","Bahmani","Bajwa","Bangial","Basra","Bhabra","Bhangra",
"Bhatti","Bhutta","Barsar","Buttar","Chaudhry","Chauhan","Chughtai","Derawal","Dhariwal","Dhillon","Dogar","Duggal",
"Gakhar","Gill","Gujjar","Gurmani","Ibrahim","Jutt","Indra","Jarral","Johiya","Kathia","Kahloon","Kalyal","Kang",
"Kayani","Khara","Khan","Kharal","Khokhar","Kirmani","Sahni","Langah","langra","langrial","Lau","Leel","Lodhra","Longi",
"Machi","Mahar","Mahtam","Makhdoom","Malik","Meghwar","Meo","Mian","Mighiana","Minhas","Mughal","Muslim Khatris",
"Rajput","Nanda","Naqvi","Paracha","Passi","Pathan","Sheikh (Punjabi)","Qaimkhani","Qureshi","Rafiq","Rajput","Ramay",
"Rana","Ranjha","Rathore","Sahi","Sahmal","Sangha","Satti","Shanzay","Sial","Siddiqui","Singh","Sidhu","Sandhu","Syed",
"Thaheem","Tiwana","Tarar","Uzair","Virk","Warraich","Abro","Arain","Bhan","Bhatti","Buriro","Chachar","Chandio",
"Daudpota","Hingora","Hingorja","Jogi","Junejo","Kalhoro","Kalwar","Khaskheli","Khoso","Khuhro","Khushk","Kumbhar",
"Lakhani","Mahesar","Mangi","Memon","Mirani","Mirbahar","Mugheri","Nizamani","Panhwar (Panwar)","Rajpar","Rind",
"Samejo","Samma","Shah","Shar","Sheedi","Siyal","Soomro","Ansari","Arain","Awan","Bhangar","Bhati","Bhutta","Bukhari",
"Chachar","Chandio","Chughtai","Durrani","Durrani","Hashmi","Kalwar","Khokhar","Khoso","Laar","Langah","Lodhra",
"Makhdoom","Noon","Panwar","Qureshi","Sahmal","Shah","Sial","Soomro","Thaheem","Bhait","Achakzai","Afridi","Awan",
"Babar","Badrashi","Bangash","Banuchi","Bettani","Burki","Chamkanni","Daulat Khel","Davi","Dawar","Dilazak","Durrani",
"Ghauri","Gandapur","Gujjar","Hafiz Khel","Isa Khel","Jadoon","Kakakhel","Kakar","Kakazai","Khalil (tribe)",
"Kharoti","Khan","Khattak","Khizarkhel","Khakwani","Khudiadadzai","Khulozai","Kuchis","Kundi","Loharani (khel)",
"Lohani (Rohani)","Lodhi","Maghdud Khel","Mahmud Khel","Mahsud","Malik","Mamund","Marwat","Mashwanis","Mian",
"Mohamedzai","Mohmand","Muhammadzai (Charsadda)","Mullagori","Musakhel","Niazi","Noorzai","Orakzai","Popalzai",
"Qazi","Rouhani","Sheikh Mohammad Rohani","Swati","Sadozai","Salarzai","Sarbani","Shilmani","Shinwari","Shirani",
"Sheikh","Sulemani","Sulemankhel","Suri","Tareen","Tarkani","Tanoli","Tokhi","Turkhel","Umar Khel","Umarzai",
"Uthman khel","Wazir","Wur","Yousafzai","Yusaf Khel","Zimri","Ansari","Bukhari","Chishti","Fareedi","Firdausi",
"Gardezi","Ghazali","Gilani","Hamadani","Hameed","Isfahani","Jadgal","Jafari","Jalali","Jamshidi","Kashani","Khorasani",
"Kermani","Askari","Mirza","Montazeri","Muker","Nishapuri","Noorani","Pirzada","Qadiri","Qizilbash","Razavi","Reza",
"Rizvi","Shirazi","Sistani","Yazdani","Zain","Zand","Abbasi","Arain","Abidi","Alvi","Barelvi","Bukhari","Baqri",
"Dhanial","Farooqi","Ghazali","Hashmi","Hassan","Hussain","Hussaini","Hyderi","Idrisi","Jafari","Kazmi","Khagga",
"Makhdoom","Mousavi","Masood","Naqvi","Najafi","Osmani","Rizvi","Sadat","Saifi","Sajjadi","Salehi","Sayyid","Shaikh",
"Siddiqui","Taqvi","Tirmizi","Turabi","Usmani","Wasti","Zubairi","Zaidi","Agha","Baig","Barlas","Gul","Mirza","Mughal","Pasha","Saadi"]